name: Run GitHub Search tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 6"

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./9_dto/9_dto

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run GitHub Search tests
      run: ./gradlew clean test

    - name: Publish test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: 9_dto/9_dto/build/reports/tests/test
